package dev.inmo.tgbotapi.types.InlineQueries.InlineQueryResult.abstracts

import dev.inmo.tgbotapi.abstracts.WithCustomizableCaption

interface WithCustomizableCaptionInlineQueryResult : InlineQueryResult, WithCustomizableCaption
