package com.github.insanusmokrassar.TelegramBotAPI.types.InlineQueries.InlineQueryResult.abstracts

import com.github.insanusmokrassar.TelegramBotAPI.CommonAbstracts.Locationed

interface PositionedInlineQueryResult : InlineQueryResult, Locationed